services:
    driver:
        build:
            context: .
            dockerfile: Dockerfile
        image: ev_driver:latest
        command:  ["EV_Driver.py","${KAFKA_IP}", "9092", "${DRIVER_ID}"] 
        stdin_open: true
        tty: true

    registry:
        build:
            context: .
            dockerfile: Dockerfile
        image: ev_registry:latest  
        command: ["EV_Registry.py"]    
        ports:
         - "8443:8443"   
        stdin_open: true
        tty: true 

    