CREATE DATABASE IF NOT EXISTS evcharging;
USE evcharging;

CREATE TABLE IF NOT EXISTS charging_point(
  id INT PRIMARY KEY,
  localizacion VARCHAR(128),
  precio DECIMAL(8,3),
  estado ENUM('ACTIVADO','PARADO','SUMINISTRANDO','AVERIADO','DESCONECTADO') DEFAULT 'DESCONECTADO',
  token VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS driver(
  id INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS openweather(
  ciudad VARCHAR(100) PRIMARY KEY,
  temp DOUBLE NOT NULL
);
